### PR TITLE
feat(mi): update exported files to include MI fields (M2-6281) (M2-5857)

### PR DESCRIPTION
**Pull request by sultanofcardio**
- [x] Tests for the changes have been added

### 📝 Description

🔗 [Jira Ticket M2-6281](https://mindlogger.atlassian.net/browse/M2-6281)
🔗 [Jira Ticket M2-5857](https://mindlogger.atlassian.net/browse/M2-5857)

The following new multi-informant fields have been added to the exported data in the `activity_user_journey.csv` and `report.csv` CSV files:

- `source_subject_id`: The subject ID of the logged in user
- `target_subject_id`: The subject ID of the person about whom the responses were given

### 📸 Screenshots

Watch the following screen recording showing the exported fields inside the CSV

https://github.com/ChildMindInstitute/mindlogger-admin/assets/14842108/5b189a12-981b-4048-b872-cb9314e63939

### 🪤 Peer Testing

> [!NOTE]
> This flow must be tested locally using the latest commit from the [feature/multiinformant-metapod](https://github.com/ChildMindInstitute/mindlogger-backend-refactor/tree/feature/multiinformant-metapod) branch of the API repository, and the latest commit from the [dev](https://github.com/ChildMindInstitute/mindlogger-web-refactor/tree/dev) branch of respondent web app repository

#### Pre-requisites

- A workspace with
  - an applet
  - An activity with at least one item
  - At least one participant (full or limited)
 - The accompanying local repositories running on the branches mentioned above

#### Steps
- Complete the take now flow a few times and submit the responses in the respondent web app
- Open the dashboard of the admin web app
- Open an applet
- Click the export button as shown in the video above
- Inspect the exported `activity_user_journey.csv` and `report.csv` CSV files and confirm the presence of the new fields.

### ✏️ Notes

The preview environment seems to be pointing to `api-dev` and `web-dev` instead of `api-dev3` and `web-dev3`, so we can't use it for this test

### CODE REVIEW

**Review by IhorNesterenko99 — DISMISSED** [review]

**Review by farmerpaul — COMMENTED** [review]
Hey @sultanofcardio, I seem to be encountering a bit of confusion and a couple issues during testing.

#### JIRA ticket description

First, I'd like to make sure I'm clear on the details. In JIRA, the description says `respondent_id` is the **subject ID of person entering data “who is filling it out?”**, which seems to be incorrect in two ways. For one, it's supposed to be a user ID, not a subject ID (which your PR description confirms). Secondly, it's not necessarily the person who is filling it out – it's the account that was signed into in order to complete the assessment – which may not be the same person who is completing the assessment. If I'm right about this, would you mind updating the JIRA ticket? Also perhaps order the fields in the ticket as `respondent_id`, `source_subject_id`, `target_subject_id`, to align with the order that the fields are exported to the CSV file (that also got me mixed up).

#### Inconsistent `respondent_id` value

Secondly, I've run some Take Now tests, and it seems that `user_id`/`respondent_id` is being populated with different values depending on whether the `target_subject_id` is referencing a full account or a limited account:

Target subject | `user_id`/`respondent_id`
-- | --
Full account | the user ID of the target subject's full account
Limited account | the user ID of the authenticated user

IMO, `respondent_id` should _always_ be the **user ID of the authenticated user** – or am I wrong? If I'm right, then there's the question of whether to align `user_id` with this definition as well, because that could impact existing users of exported data.

#### Export caching?

Lastly, I'm finding that when I re-export the CSV file within the same login session of the admin app, it doesn't seem to get regenerated with the most recently completed "Take Now" assessments. I seem to have to log out of the admin app, and log back in, and then that export has the latest additions. Are you finding this?

**Comment by sultanofcardio** [comment]
Hey @farmerpaul thanks for the review. Let me see if I can help clear up some of the issues you ran into.

> In JIRA, the description says `respondent_id` is the **subject ID of person entering data “who is filling it out?”**, which seems to be incorrect in two ways. For one, it's supposed to be a user ID, not a subject ID (which your PR description confirms). Secondly, it's not necessarily the person who is filling it out – it's the account that was signed into in order to complete the assessment – which may not be the same person who is completing the assessment.

You're correct about the respondent ID being a user ID. I missed this detail of the ticket because of my existing knowledge of the solution, so thanks for catching this. I will ask for it to be updated.

Regarding it not necessarily being the person who is filling it out, that wording is making reference to Q2 of [M2-6480](https://mindlogger.atlassian.net/browse/M2-6480). For this first release, the person filling out the assessment and the person logged in will be the same. In order to accommodate the scenario where they are not the same, further adjustments will need to be made; that scenario is not yet supported. Nevertheless, I believe this can be made clearer in the ticket description so I will also ask for this to be updated.

> Secondly, I've run some Take Now tests, and it seems that user_id/respondent_id is being populated with different values depending on whether the target_subject_id is referencing a full account or a limited account

I hadn't run this test. Since you raised it I've tested it out and it seems that the API is always setting the `respondent_id` to be the corresponding user ID of the `target_subject_id`. That means that in the case of a limited account, the field is empty because they don't have user IDs. The consequence of this is the same applies for the `user_id` field. This will need to be addressed on the BE, perhaps in a new ticket.

> I'm finding that when I re-export the CSV file within the same login session of the admin app, it doesn't seem to get regenerated with the most recently completed "Take Now" assessments. I seem to have to log out of the admin app, and log back in, and then that export has the latest additions. Are you finding this?

This is a consequence of the `toDate` field being tied to the date range dropdown field in the popup. The `toDate` only changes when you change the value of that field, or refresh the page. So if you complete an assessment since you loaded the page, doing an export will use the `toDate` from when the page was originally loaded, and exclude the new data.

Technically it's outside the scope of this ticket, but it's probably a small enough change for a good UX improvement that I can address it. Thanks for pointing it out

 

[M2-6480]: https://mindlogger.atlassian.net/browse/M2-6480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by farmerpaul — DISMISSED** [review]
Thanks for fixing that stale export bug! And for explaining the context of that `respondent_id`/`user_id` bug, which I get is a BE issue. Approving!

**Comment by sultanofcardio** [comment]
@farmerpaul the requirements on this ticket have changed as a result of ongoing multi-informant discussions. The result is that the `respondent_id` column has been removed from this ticket, and I've updated the code to reflect that in the exported files. I've also added [M2-5857](https://mindlogger.atlassian.net/browse/M2-5857) to this PR since it's a closely related change.

Can you please give a re-review when you get a chance?

[M2-5857]: https://mindlogger.atlassian.net/browse/M2-5857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Review by farmerpaul — APPROVED** [review]

**Pull request merged**
