### PR TITLE
fix: PDF reports for duplicated applets that include Report Server Configuration (M2-8057)

### PR DESCRIPTION
**Pull request by mbanting**
- [ ] Delivered the `fix` or `feature` branches into `develop` or `release` branches via `Squash and Merge` (to keep clean history)

### 📝 Description

🔗 [Jira Ticket M2-8057](https://mindlogger.atlassian.net/browse/M2-8057)

This fixes an issue with the new Duplicate Applet functionality when including the Report Server Configuration (implemented in [M2-7729](https://mindlogger.atlassian.net/browse/M2-8057)). The PDF report was not generating successfully with these duplicated applets. 

Determined the cause of this was the Admin Panel sending an empty password to the Report Server during replication (via the report server's `set-password` endpoint). This was because the `encryptionDataRef` was getting reset in the finally clause of the `useAsync` call to `duplicateAppletApi`, _before_ the report server configuration setup had a chance to complete.

Changes include:

- Updates `useAsync` of `duplicateAppletApi` by moving cleanup out of the `finally` callback, and instead handles the `encryptionDataRef` cleanup on both success and error callbacks separately, ensuring cleanup takes place after it is no longer needed. 

### 📸 Screenshots

https://www.loom.com/share/c2f01f6aa6cf4b91a9d60197b1753214?sid=02575f6e-3b68-4a9e-919c-2bf375814ced

### 🪤 Peer Testing

1. Setup an Applet with a single activity and item with scoring
2. Configure the Applet's Report Configuration and use one of the existing Report Servers (recommend [UAT](https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/348684325/Credentials#UAT-env))
3. Configure the activity's Scores & Reports to Generate Report and Show Score Summary, and configure a Score
4. Save & Publish the Applet
5. Complete the activity (feel free to initiate it via Take Now)
6. Confirm a report was received (this is existing functionality)
7. Go back to Admin and duplicate the applet, including Report Server configuration
8. Go to duplicate applet's Report Configuration and enter an email (since it is not duplicated from original applet)
9. Complete the activity of the duplicated applet (feel free to initiate it via Take Now)
10.  **Expected outcome:** a PDF report is received

### ✏️ Notes

- https://github.com/ChildMindInstitute/mindlogger-admin/pull/1942

[M2-7729]: https://mindlogger.atlassian.net/browse/M2-7729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by farmerpaul — APPROVED** [review]
Hey @mbanting, the code looks good to me. I guess this `useAsync` hook doesn't actually handle async callbacks by awaiting them, else this might not have been an issue – is that right?

I trust that this fix solves the issue, but unfortunately I'm unable to get my local environment to email me a PDF report at all – step 6 in your Peer Testing section – even though I've double- and triple-checked that I have everything configured right. I assume that despite my checks, I still don't have something properly set up to get it to work. The whole reporting and scoring feature of MindLogger has been very difficult for me to wrap my head around.

I'll pre-approve because I trust your judgment!

**Review by LashaunnaS — APPROVED** [review]
I was able to successfully reproduce the expected behavior. ✅

**Comment by mbanting** [comment]
> Hey @mbanting, the code looks good to me. I guess this `useAsync` hook doesn't actually handle async callbacks by awaiting them, else this might not have been an issue – is that right?
> 
> I trust that this fix solves the issue, but unfortunately I'm unable to get my local environment to email me a PDF report at all – step 6 in your Peer Testing section – even though I've double- and triple-checked that I have everything configured right. I assume that despite my checks, I still don't have something properly set up to get it to work. The whole reporting and scoring feature of MindLogger has been very difficult for me to wrap my head around.
> 
> I'll pre-approve because I trust your judgment!

Thanks @farmerpaul !

The issue wasn't with useAsync not awaiting correctly—it does handle async callbacks properly (I think). The real issue was that the code needing `encryptionDataRef` was in a `useEffect`, which runs asynchronously and independent of the callbacks, including the finally callback that was resetting the data.

**Comment by farmerpaul** [comment]
> The issue wasn't with useAsync not awaiting correctly—it does handle async callbacks properly (I think). The real issue was that the code needing encryptionDataRef was in a useEffect, which runs asynchronously and independent of the callbacks, including the finally callback that was resetting the data.

What I mean is that `useAsync` doesn't handle asynchronous _success and error callbacks_. It _does_ properly handle the asynchronous nature of the _main callback_ that's passed to the hook, but I think it disregards any asynchronous nature of the success and error callbacks.

So for example, if the `successCallback` happens to be an async one and returns a Promise, that return value is discarded – the hook doesn't `await` it [here](https://github.com/ChildMindInstitute/mindlogger-admin/blob/a55547a273aa2798fa9b264f2481b71cbb860d40/src/shared/hooks/useAsync/useAsync.ts#L65), before finishing the `then()` condition. That means the `finallyCallback` will run even if the `successCallback` is still busy doing things asynchronously.

**Comment by mbanting** [comment]
> > The issue wasn't with useAsync not awaiting correctly—it does handle async callbacks properly (I think). The real issue was that the code needing encryptionDataRef was in a useEffect, which runs asynchronously and independent of the callbacks, including the finally callback that was resetting the data.
> 
> What I mean is that `useAsync` doesn't handle asynchronous _success and error callbacks_. It _does_ properly handle the asynchronous nature of the _main callback_ that's passed to the hook, but I think it disregards any asynchronous nature of the success and error callbacks.
> 
> So for example, if the `successCallback` happens to be an async one and returns a Promise, that return value is discarded – the hook doesn't `await` it [here](https://github.com/ChildMindInstitute/mindlogger-admin/blob/a55547a273aa2798fa9b264f2481b71cbb860d40/src/shared/hooks/useAsync/useAsync.ts#L65), before finishing the `then()` condition. That means the `finallyCallback` will run even if the `successCallback` is still busy doing things asynchronously.

Oh I see what you're referring to. Yes that is also true! Looks like `useAsync` isn't designed to handle async success or error callbacks.

**Comment by mbanting** [comment]
Thanks for the review @LashaunnaS @farmerpaul !

**Pull request merged**
