### PR TITLE
fix: update copy in MI Assign help dialogue (M2-7317)

### PR DESCRIPTION
**Pull request by AlejandroCoronadoN**
### 📝 Description

🔗 [Jira Ticket M2-7317](https://mindlogger.atlassian.net/browse/M2-7317)

As an admin, I want to see help text when I click the :question_mark: button so that I can easily understand the functionality and purpose of Assign.

- [ ] Replaced english and french version of HelpContent for activities help popup.
- [ ] Reused styled components for titles and parragraphs using Trans. 
- [ ] Replaced French Version

### 📸 Screenshots
image

### 🪤 Peer Testing
- Log into the admin app.
- Create an activity.
- Go to the Activities tab
- Inside activities, you created activity should be dispalyed. 
- Click on "Assign" button on the rightside
-Click on the  :question_mark:  button to display the content

### ✏️ Notes
- The content in the Sigma file is different from the content on the Jira Ticket. I used Jira information since it looked more complete.
- Not sure if I should add hyperlinks from Jira.

### CODE REVIEW

**Comment by farmerpaul** [comment]
Hi @AlejandroCoronadoN, just another reminder about PR best practices:
1. Avoid deleting this line from the PR description template to support automation and add 1-click access to the Jira ticket:
    ```
    🔗 [Jira Ticket M2-7317](https://mindlogger.atlassian.net/browse/M2-7317)
    ```
2. Use the PR format as specified in our shared [PR authoring guidelines](https://mindlogger.atlassian.net/wiki/spaces/MINDLOGGER1/pages/7503873/Configuration+Management+Plan#Pull-Requests):

    **type**_(optional scope)_: **brief summary (M2-####**[, additional tickets]**)**
    
    So in this case, I'd recommend:
    
    ```
    fix: update copy in MI Assign help dialogue (M2-7317)
    ```

Thanks!

**Comment by AlejandroCoronadoN** [comment]
@farmerpaul I made the changes, thanks for the comments, I think I copied this format from an old Backend PR but you are right. I'll be using this title format from now on. Also, I will add the Jira link and tag from now on.

**Review by farmerpaul — APPROVED** [review]
Looks good, @AlejandroCoronadoN! Approving.

Even though you mentioned that you fix the PR title, for some reason it was still showing the old version… 🤔 



So I hope you don't mind, I just went ahead and updated it to the suggested one `fix: update copy in MI Assign help dialogue (M2-7317)`.

Also, just a reminder to follow the **new QA workflow** for the admin & web app: Do not merge this yet. Instead, set the Jira task's status to "TO BE TESTED" (or move the task to the "FQA - READY" column). Katty will assign it to herself, and then test your work in the PR's Amplify preview env, and once she sets the status to "READY TO MERGE", you can merge it! 🚀

**Review by mbanting — APPROVED** [review]

**Comment by mbanting** [comment]
@AlejandroCoronadoN as mentioned above, with these two approvals please return back to the JIRA ticket and mark as To Be Tested so that @kattyode knows to begin QAing this in this PR's feature environment.

**Pull request merged**
